name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello, world!"

      - name: Another greeting
        run: echo "Hello, world!"

  log-variable:
    runs-on: ubuntu-latest
    outputs:
      failures: ${{ steps.set-variable.outputs.fail_count }}
      report: ${{ steps.set-variable.outputs.fail_report }}
      report_1: ${{ steps.set-variable.outputs.fail_report_1 }}
      report_2: ${{ steps.set-variable.outputs.fail_report_2 }}

    steps:
      - uses: actions/checkout@v2

      - name: Set variable
        id: set-variable
        run: |
          if [ -f "index.json" ] 
          then
          full_report=""
          limit=3

          total_fails=`cat index.json | jq ".stats.failures"`

          fail_results=`cat index.json | jq -c '.results[].suites[] | select(.failures | length > 0)'`

          jq -c "$fail_results" index.json | while read -r i && [[ $limit != 0 ]]; do
              title=$(echo "$i" | jq '.tests[0].title')
              file=$(echo "$i" | jq '.fullFile')
              message=$(echo "$i" | jq '.tests[0].err.message')
              run_id=$(echo "$i" | jq '.uuid')

              report=$(echo ":test_tube:*TEST*: $title \n:open_file_folder:*FILE*: <https://cypress-dashboard.staging.manabie.io:31600/instance/$run_id | $file> \n:speech_balloon:*MESSAGE*: $message \n")

              full_report+="$report /n"
              ((limit--))
             
              full_report=$(echo ${full_report//$'\n'/'%0A'} | sed 's/"//g')
              echo "::set-output name=fail_count::$total_fails"
              echo "::set-output name=fail_report::$full_report"
          done
          else
            echo "No Failed Tests"
          fi

      - name: Check report
        id: check-report
        run: |
          echo "${{ steps.set-variable.outputs.fail_report }} - +++FAILURESSS"

  slack-reporter:
    runs-on: ubuntu-latest
    needs:
      - build
      - log-variable

    steps:
      - name: Check variable
        id: check-variable
        run: |
          echo "${{ needs.log-variable.outputs.failures }} - +++FAILURESSS"
          echo "${{ needs.log-variable.outputs.report }} - +++REPORT"
          echo "${{ needs.log-variable.outputs.report_1 }} - +++REPORT 1"
          echo "${{ needs.log-variable.outputs.report_2 }} - +++REPORT 2"
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=pull-request-number::"${pull_number}""

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload-file-path: "./slack-payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
