name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello, world!"

      - name: Another greeting
        run: echo "Hello, world!"

  log-variable:
    runs-on: ubuntu-latest
    outputs:
      failures: ${{ steps.set-variable.outputs.fail_count }}
      report: ${{ steps.set-variable.outputs.fail_report }}
      report_1: ${{ steps.set-variable.outputs.fail_report_1 }}
      report_2: ${{ steps.set-variable.outputs.fail_report_2 }}

    steps:
      - uses: actions/checkout@v2

      - name: Set variable
        id: set-variable
        run: |
          bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/cypress-fail-report-transformer.bash"

      - name: Check report
        id: check-report
        run: |
          echo "${{ steps.set-variable.outputs.fail_report }} - +++FAILURESSS"

  slack-reporter:
    runs-on: ubuntu-latest
    needs:
      - build
      - log-variable

    steps:
      - uses: actions/checkout@v2
    
      - name: Check variable
        id: check-variable
        run: |
          echo $PWD
          echo "${{ needs.log-variable.outputs.failures }} - +++FAILURESSS"
          echo "${{ needs.log-variable.outputs.report }} - +++REPORT"
          echo "${{ needs.log-variable.outputs.report_1 }} - +++REPORT 1"
          echo "${{ needs.log-variable.outputs.report_2 }} - +++REPORT 2"
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=pull-request-number::"${pull_number}""

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload-file-path: "./.github/workflows/slack-payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
